























.build/mega2560/StepperControl/StepperControl.o : lib/StepperControl/StepperControl.cpp
	@echo [93mStepperControl/StepperControl.cpp[0m
	@mkdir -p .build/mega2560/StepperControl
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/StepperControl/StepperControl.cpp
include .build/mega2560/StepperControl/StepperControl.d



.build/mega2560/StepperControl/libStepperControl.a : .build/mega2560/StepperControl/StepperControl.o
	@echo [92mLinking libStepperControl.a[0m
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build/mega2560/PTP_2.0/canoneos.o : lib/PTP_2.0/canoneos.cpp
	@echo [93mPTP_2.0/canoneos.cpp[0m
	@mkdir -p .build/mega2560/PTP_2.0
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/PTP_2.0/canoneos.cpp
include .build/mega2560/PTP_2.0/canoneos.d

.build/mega2560/PTP_2.0/canonps.o : lib/PTP_2.0/canonps.cpp
	@echo [93mPTP_2.0/canonps.cpp[0m
	@mkdir -p .build/mega2560/PTP_2.0
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/PTP_2.0/canonps.cpp
include .build/mega2560/PTP_2.0/canonps.d

.build/mega2560/PTP_2.0/eoseventdump.o : lib/PTP_2.0/eoseventdump.cpp
	@echo [93mPTP_2.0/eoseventdump.cpp[0m
	@mkdir -p .build/mega2560/PTP_2.0
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/PTP_2.0/eoseventdump.cpp
include .build/mega2560/PTP_2.0/eoseventdump.d

.build/mega2560/PTP_2.0/eoseventparser.o : lib/PTP_2.0/eoseventparser.cpp
	@echo [93mPTP_2.0/eoseventparser.cpp[0m
	@mkdir -p .build/mega2560/PTP_2.0
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/PTP_2.0/eoseventparser.cpp
include .build/mega2560/PTP_2.0/eoseventparser.d

.build/mega2560/PTP_2.0/nikon.o : lib/PTP_2.0/nikon.cpp
	@echo [93mPTP_2.0/nikon.cpp[0m
	@mkdir -p .build/mega2560/PTP_2.0
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/PTP_2.0/nikon.cpp
include .build/mega2560/PTP_2.0/nikon.d

.build/mega2560/PTP_2.0/nkeventparser.o : lib/PTP_2.0/nkeventparser.cpp
	@echo [93mPTP_2.0/nkeventparser.cpp[0m
	@mkdir -p .build/mega2560/PTP_2.0
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/PTP_2.0/nkeventparser.cpp
include .build/mega2560/PTP_2.0/nkeventparser.d

.build/mega2560/PTP_2.0/ptp.o : lib/PTP_2.0/ptp.cpp
	@echo [93mPTP_2.0/ptp.cpp[0m
	@mkdir -p .build/mega2560/PTP_2.0
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/PTP_2.0/ptp.cpp
include .build/mega2560/PTP_2.0/ptp.d

.build/mega2560/PTP_2.0/ptpconstitles.o : lib/PTP_2.0/ptpconstitles.cpp
	@echo [93mPTP_2.0/ptpconstitles.cpp[0m
	@mkdir -p .build/mega2560/PTP_2.0
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/PTP_2.0/ptpconstitles.cpp
include .build/mega2560/PTP_2.0/ptpconstitles.d

.build/mega2560/PTP_2.0/simpletimer.o : lib/PTP_2.0/simpletimer.cpp
	@echo [93mPTP_2.0/simpletimer.cpp[0m
	@mkdir -p .build/mega2560/PTP_2.0
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/PTP_2.0/simpletimer.cpp
include .build/mega2560/PTP_2.0/simpletimer.d



.build/mega2560/PTP_2.0/libPTP_2.a : .build/mega2560/PTP_2.0/canoneos.o .build/mega2560/PTP_2.0/canonps.o .build/mega2560/PTP_2.0/eoseventdump.o .build/mega2560/PTP_2.0/eoseventparser.o .build/mega2560/PTP_2.0/nikon.o .build/mega2560/PTP_2.0/nkeventparser.o .build/mega2560/PTP_2.0/ptp.o .build/mega2560/PTP_2.0/ptpconstitles.o .build/mega2560/PTP_2.0/simpletimer.o
	@echo [92mLinking libPTP_2.a[0m
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build/mega2560/USBHost/adk.o : lib/USBHost/adk.cpp
	@echo [93mUSBHost/adk.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/adk.cpp
include .build/mega2560/USBHost/adk.d

.build/mega2560/USBHost/BTD.o : lib/USBHost/BTD.cpp
	@echo [93mUSBHost/BTD.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/BTD.cpp
include .build/mega2560/USBHost/BTD.d

.build/mega2560/USBHost/cdcacm.o : lib/USBHost/cdcacm.cpp
	@echo [93mUSBHost/cdcacm.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/cdcacm.cpp
include .build/mega2560/USBHost/cdcacm.d

.build/mega2560/USBHost/cdcftdi.o : lib/USBHost/cdcftdi.cpp
	@echo [93mUSBHost/cdcftdi.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/cdcftdi.cpp
include .build/mega2560/USBHost/cdcftdi.d

.build/mega2560/USBHost/cdcprolific.o : lib/USBHost/cdcprolific.cpp
	@echo [93mUSBHost/cdcprolific.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/cdcprolific.cpp
include .build/mega2560/USBHost/cdcprolific.d

.build/mega2560/USBHost/examples/HID/le3dp/le3dp_rptparser.o : lib/USBHost/examples/HID/le3dp/le3dp_rptparser.cpp
	@echo [93mUSBHost/examples/HID/le3dp/le3dp_rptparser.cpp[0m
	@mkdir -p .build/mega2560/USBHost/examples/HID/le3dp
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/examples/HID/le3dp/le3dp_rptparser.cpp
include .build/mega2560/USBHost/examples/HID/le3dp/le3dp_rptparser.d

.build/mega2560/USBHost/examples/HID/USBHIDJoystick/hidjoystickrptparser.o : lib/USBHost/examples/HID/USBHIDJoystick/hidjoystickrptparser.cpp
	@echo [93mUSBHost/examples/HID/USBHIDJoystick/hidjoystickrptparser.cpp[0m
	@mkdir -p .build/mega2560/USBHost/examples/HID/USBHIDJoystick
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/examples/HID/USBHIDJoystick/hidjoystickrptparser.cpp
include .build/mega2560/USBHost/examples/HID/USBHIDJoystick/hidjoystickrptparser.d

.build/mega2560/USBHost/hid.o : lib/USBHost/hid.cpp
	@echo [93mUSBHost/hid.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/hid.cpp
include .build/mega2560/USBHost/hid.d

.build/mega2560/USBHost/hidboot.o : lib/USBHost/hidboot.cpp
	@echo [93mUSBHost/hidboot.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/hidboot.cpp
include .build/mega2560/USBHost/hidboot.d

.build/mega2560/USBHost/hidescriptorparser.o : lib/USBHost/hidescriptorparser.cpp
	@echo [93mUSBHost/hidescriptorparser.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/hidescriptorparser.cpp
include .build/mega2560/USBHost/hidescriptorparser.d

.build/mega2560/USBHost/hiduniversal.o : lib/USBHost/hiduniversal.cpp
	@echo [93mUSBHost/hiduniversal.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/hiduniversal.cpp
include .build/mega2560/USBHost/hiduniversal.d

.build/mega2560/USBHost/hidusagetitlearrays.o : lib/USBHost/hidusagetitlearrays.cpp
	@echo [93mUSBHost/hidusagetitlearrays.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/hidusagetitlearrays.cpp
include .build/mega2560/USBHost/hidusagetitlearrays.d

.build/mega2560/USBHost/masstorage.o : lib/USBHost/masstorage.cpp
	@echo [93mUSBHost/masstorage.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/masstorage.cpp
include .build/mega2560/USBHost/masstorage.d

.build/mega2560/USBHost/max_LCD.o : lib/USBHost/max_LCD.cpp
	@echo [93mUSBHost/max_LCD.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/max_LCD.cpp
include .build/mega2560/USBHost/max_LCD.d

.build/mega2560/USBHost/message.o : lib/USBHost/message.cpp
	@echo [93mUSBHost/message.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/message.cpp
include .build/mega2560/USBHost/message.d

.build/mega2560/USBHost/parsetools.o : lib/USBHost/parsetools.cpp
	@echo [93mUSBHost/parsetools.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/parsetools.cpp
include .build/mega2560/USBHost/parsetools.d

.build/mega2560/USBHost/PS3BT.o : lib/USBHost/PS3BT.cpp
	@echo [93mUSBHost/PS3BT.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/PS3BT.cpp
include .build/mega2560/USBHost/PS3BT.d

.build/mega2560/USBHost/PS3USB.o : lib/USBHost/PS3USB.cpp
	@echo [93mUSBHost/PS3USB.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/PS3USB.cpp
include .build/mega2560/USBHost/PS3USB.d

.build/mega2560/USBHost/SPP.o : lib/USBHost/SPP.cpp
	@echo [93mUSBHost/SPP.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/SPP.cpp
include .build/mega2560/USBHost/SPP.d

.build/mega2560/USBHost/Usb.o : lib/USBHost/Usb.cpp
	@echo [93mUSBHost/Usb.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/Usb.cpp
include .build/mega2560/USBHost/Usb.d

.build/mega2560/USBHost/usbhub.o : lib/USBHost/usbhub.cpp
	@echo [93mUSBHost/usbhub.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/usbhub.cpp
include .build/mega2560/USBHost/usbhub.d

.build/mega2560/USBHost/Wii.o : lib/USBHost/Wii.cpp
	@echo [93mUSBHost/Wii.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/Wii.cpp
include .build/mega2560/USBHost/Wii.d

.build/mega2560/USBHost/XBOXRECV.o : lib/USBHost/XBOXRECV.cpp
	@echo [93mUSBHost/XBOXRECV.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/XBOXRECV.cpp
include .build/mega2560/USBHost/XBOXRECV.d

.build/mega2560/USBHost/XBOXUSB.o : lib/USBHost/XBOXUSB.cpp
	@echo [93mUSBHost/XBOXUSB.cpp[0m
	@mkdir -p .build/mega2560/USBHost
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/USBHost/XBOXUSB.cpp
include .build/mega2560/USBHost/XBOXUSB.d



.build/mega2560/USBHost/libUSBHost.a : .build/mega2560/USBHost/adk.o .build/mega2560/USBHost/BTD.o .build/mega2560/USBHost/cdcacm.o .build/mega2560/USBHost/cdcftdi.o .build/mega2560/USBHost/cdcprolific.o .build/mega2560/USBHost/examples/HID/le3dp/le3dp_rptparser.o .build/mega2560/USBHost/examples/HID/USBHIDJoystick/hidjoystickrptparser.o .build/mega2560/USBHost/hid.o .build/mega2560/USBHost/hidboot.o .build/mega2560/USBHost/hidescriptorparser.o .build/mega2560/USBHost/hiduniversal.o .build/mega2560/USBHost/hidusagetitlearrays.o .build/mega2560/USBHost/masstorage.o .build/mega2560/USBHost/max_LCD.o .build/mega2560/USBHost/message.o .build/mega2560/USBHost/parsetools.o .build/mega2560/USBHost/PS3BT.o .build/mega2560/USBHost/PS3USB.o .build/mega2560/USBHost/SPP.o .build/mega2560/USBHost/Usb.o .build/mega2560/USBHost/usbhub.o .build/mega2560/USBHost/Wii.o .build/mega2560/USBHost/XBOXRECV.o .build/mega2560/USBHost/XBOXUSB.o
	@echo [92mLinking libUSBHost.a[0m
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^







.build/mega2560/arduino/malloc.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/malloc.c
	@echo [93marduino/malloc.c[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/malloc.c
include .build/mega2560/arduino/malloc.d

.build/mega2560/arduino/WInterrupts.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WInterrupts.c
include .build/mega2560/arduino/WInterrupts.d

.build/mega2560/arduino/wiring.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring.c
include .build/mega2560/arduino/wiring.d

.build/mega2560/arduino/wiring_analog.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_analog.c
include .build/mega2560/arduino/wiring_analog.d

.build/mega2560/arduino/wiring_digital.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_digital.c
include .build/mega2560/arduino/wiring_digital.d

.build/mega2560/arduino/wiring_pulse.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_pulse.c
include .build/mega2560/arduino/wiring_pulse.d

.build/mega2560/arduino/wiring_shift.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_shift.c
include .build/mega2560/arduino/wiring_shift.d






.build/mega2560/arduino/CDC.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/CDC.cpp
include .build/mega2560/arduino/CDC.d

.build/mega2560/arduino/HardwareSerial.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/HardwareSerial.cpp
include .build/mega2560/arduino/HardwareSerial.d

.build/mega2560/arduino/HID.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/HID.cpp
	@echo [93marduino/HID.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/HID.cpp
include .build/mega2560/arduino/HID.d

.build/mega2560/arduino/IPAddress.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/IPAddress.cpp
include .build/mega2560/arduino/IPAddress.d

.build/mega2560/arduino/main.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/main.cpp
include .build/mega2560/arduino/main.d

.build/mega2560/arduino/new.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/new.cpp
include .build/mega2560/arduino/new.d

.build/mega2560/arduino/Print.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Print.cpp
include .build/mega2560/arduino/Print.d

.build/mega2560/arduino/Stream.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Stream.cpp
include .build/mega2560/arduino/Stream.d

.build/mega2560/arduino/Tone.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Tone.cpp
include .build/mega2560/arduino/Tone.d

.build/mega2560/arduino/USBCore.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/USBCore.cpp
include .build/mega2560/arduino/USBCore.d

.build/mega2560/arduino/WMath.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WMath.cpp
include .build/mega2560/arduino/WMath.d

.build/mega2560/arduino/WString.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WString.cpp
include .build/mega2560/arduino/WString.d



.build/mega2560/arduino/libarduino.a : .build/mega2560/arduino/malloc.o .build/mega2560/arduino/WInterrupts.o .build/mega2560/arduino/wiring.o .build/mega2560/arduino/wiring_analog.o .build/mega2560/arduino/wiring_digital.o .build/mega2560/arduino/wiring_pulse.o .build/mega2560/arduino/wiring_shift.o .build/mega2560/arduino/CDC.o .build/mega2560/arduino/HardwareSerial.o .build/mega2560/arduino/HID.o .build/mega2560/arduino/IPAddress.o .build/mega2560/arduino/main.o .build/mega2560/arduino/new.o .build/mega2560/arduino/Print.o .build/mega2560/arduino/Stream.o .build/mega2560/arduino/Tone.o .build/mega2560/arduino/USBCore.o .build/mega2560/arduino/WMath.o .build/mega2560/arduino/WString.o
	@echo [92mLinking libarduino.a[0m
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build/mega2560/src/devpropparser.o : src/devpropparser.cpp
	@echo [93msrc/devpropparser.cpp[0m
	@mkdir -p .build/mega2560/src
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c src/devpropparser.cpp
include .build/mega2560/src/devpropparser.d

.build/mega2560/src/foto360.o : .build/mega2560/src/foto360.cpp
	@echo [93msrc/foto360.cpp[0m
	@mkdir -p .build/mega2560/src
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/StepperControl -Ilib/PTP_2.0 -Ilib/USBHost -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions -iquote src  -o $@ -c .build/mega2560/src/foto360.cpp
include .build/mega2560/src/foto360.d







.build/mega2560/firmware.elf : .build/mega2560/src/devpropparser.o .build/mega2560/src/foto360.o .build/mega2560/StepperControl/libStepperControl.a .build/mega2560/PTP_2.0/libPTP_2.a .build/mega2560/USBHost/libUSBHost.a .build/mega2560/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -Os -Wl,--gc-sections -mmcu=atmega2560 -o $@ $^ -lm


.build/mega2560/firmware.hex : .build/mega2560/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/mega2560/src/dependencies.d .build/mega2560/arduino/dependencies.d .build/mega2560/StepperControl/dependencies.d .build/mega2560/PTP_2.0/dependencies.d .build/mega2560/USBHost/dependencies.d

all : .build/mega2560/firmware.hex
	@true

