




.build/mega2560/src/foto360.cpp : src/foto360.ino
	@mkdir -p .build/mega2560/src
	@echo [93msrc/foto360.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/mega2560/src/foto360.cpp
	@true

